### ISSUE TITLE
Remove the API keys from index.js

### ISSUE THREAD

**Issue by AyushAjay14** [anish2210/web-dev-2023#3]
You have left your API keys in the index.js file. It is not recommended to leave your keys in the repository instead use a .env file.

**Comment by abhishek-kumar-91** [comment]
I want to work on this issue, Can you assign me?

**Comment by Shivam-SG** [comment]
i can fix this issue, please assign me this project

**Comment by anish2210** [comment]
> I want to work on this issue, Can you assign me?

you just need to add one of your web dev project here to be a part of hacktoberfest.
